#!/usr/bin/env bash
# Deploy this built mod into the game's mods/ folder (DEPLOY_DIR in config.sh).
#
# Clean replace: DEPLOY_DIR/<mod-id>/ ends up exactly matching this mod's
# build/<mod-id>/. config.json and settings.json are regenerated by the game/mod
# on next launch, so they are intentionally not preserved.
set -euo pipefail
cd "$(dirname "$0")"
source ./config.sh

NAME="$(basename "$PWD")"
BUILT="build/$NAME"
if [[ ! -d "$BUILT" ]]; then
    echo "deploy: nothing built at '$BUILT' -- run build.sh first" >&2
    exit 1
fi

DEST="$DEPLOY_DIR/$NAME"
rm -rf "$DEST"
mkdir -p "$DEST"
cp -rf "$BUILT/." "$DEST/"
echo "Deployed '$NAME' -> $DEST"
